name: Release with Tagged Zip

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set Zip Name
        id: vars
        run: |
          PACKAGE_NAME="AutoEditorOnlyConverter"
          echo "zip_name=${PACKAGE_NAME}-${{ github.ref_name }}.zip" >> $GITHUB_OUTPUT

      - name: Create Zip
        run: |
          git archive --format=tar HEAD | 7z a -si ${{ steps.vars.outputs.zip_name }}

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.vars.outputs.zip_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
